"""Deterministic fallback question bank.
Used when DB or AI models need supplementary curriculum questions or offline generation,
so the app always generates age-appropriate, subject-specific questions for any grade and question count.
"""

KIDS_QUESTION_BANKS = {
    "computer science": [
        {
            "type": "mcq",
            "questionText": "Which part of a computer looks like a TV screen and displays our work? 🖥️",
            "options": ["A) Monitor", "B) Keyboard", "C) Mouse", "D) CPU"],
            "correctAnswer": "A",
            "explanation": "A Monitor is the visual display unit that shows pictures, text, and videos on the computer.",
            "topic": "Parts of a Computer",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which key is the longest key on the keyboard and is used to give spaces between words? ⌨️",
            "options": ["A) Enter Key", "B) Spacebar", "C) Shift Key", "D) Backspace"],
            "correctAnswer": "B",
            "explanation": "The Spacebar is the longest horizontal key on the keyboard used to insert space between words.",
            "topic": "Keyboard Skills",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which device is known as the 'Brain of the Computer'? 🧠",
            "options": ["A) Mouse", "B) Monitor", "C) CPU", "D) Printer"],
            "correctAnswer": "C",
            "explanation": "CPU (Central Processing Unit) performs all calculations and controls all parts of the computer.",
            "topic": "Computer Fundamentals",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What hand-held device has 2 buttons and a scroll wheel to point and click on items? 🖱️",
            "options": ["A) Mouse", "B) Microphone", "C) Speaker", "D) Scanner"],
            "correctAnswer": "A",
            "explanation": "A computer mouse is a pointing device used to click, double click, and drag items.",
            "topic": "Input Devices",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which key do we press to start typing on a new line? ↵",
            "options": ["A) Caps Lock", "B) Enter Key", "C) Escape Key", "D) Delete Key"],
            "correctAnswer": "B",
            "explanation": "The Enter key moves the cursor to the beginning of the next line.",
            "topic": "Keyboard Skills",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which output device is used to print our drawings and stories on paper? 🖨️",
            "options": ["A) Printer", "B) Webcam", "C) Keyboard", "D) Joystick"],
            "correctAnswer": "A",
            "explanation": "A printer produces a paper copy (hard copy) of documents stored in the computer.",
            "topic": "Output Devices",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What software program is used to draw and color digital pictures on the computer? 🎨",
            "options": ["A) MS Paint", "B) Calculator", "C) Notepad", "D) Media Player"],
            "correctAnswer": "A",
            "explanation": "MS Paint is a simple graphics painting program included with Microsoft Windows.",
            "topic": "Fun Tools & Paint",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which key turns on CAPITAL letters when you type words? 🔠",
            "options": ["A) Caps Lock", "B) Spacebar", "C) Backspace", "D) Arrow Key"],
            "correctAnswer": "A",
            "explanation": "Pressing the Caps Lock key allows all typed letters to appear in UPPERCASE.",
            "topic": "Keyboard Skills",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which device helps us listen to music and games from our computer? 🔊",
            "options": ["A) Speakers", "B) Scanner", "C) Keyboard", "D) Mouse"],
            "correctAnswer": "A",
            "explanation": "Speakers output audio sound signals so we can hear songs, voices, and game effects.",
            "topic": "Output Devices",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which tool in Paint allows you to fill a whole shape with your favorite color? 🪣",
            "options": ["A) Fill with Color (Bucket)", "B) Pencil Tool", "C) Eraser Tool", "D) Magnifier"],
            "correctAnswer": "A",
            "explanation": "The 'Fill with Color' bucket tool floods any closed boundary or shape with color.",
            "topic": "Fun Tools & Paint",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "A small blinking vertical line on the monitor that shows where you will type next is called: ✍️",
            "options": ["A) Cursor", "B) Icon", "C) Desktop", "D) Taskbar"],
            "correctAnswer": "A",
            "explanation": "The Cursor is the blinking mark that indicates your current typing position.",
            "topic": "Typing Basics",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which portable computer can easily sit on your lap and run on battery? 💻",
            "options": ["A) Laptop", "B) Supercomputer", "C) Mainframe", "D) Server Tower"],
            "correctAnswer": "A",
            "explanation": "A laptop is a compact, portable computer that you can carry and use anywhere.",
            "topic": "Types of Computers",
            "marks": 1,
        },
    ],
    "mathematics": [
        {
            "type": "mcq",
            "questionText": "What is the sum of 25 + 15? ➕",
            "options": ["A) 40", "B) 35", "C) 50", "D) 45"],
            "correctAnswer": "A",
            "explanation": "25 + 15 = 40.",
            "topic": "Addition",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "How many sides does a triangle have? 🔺",
            "options": ["A) 3", "B) 4", "C) 5", "D) 2"],
            "correctAnswer": "A",
            "explanation": "A triangle is a closed geometric shape with exactly 3 straight sides and 3 angles.",
            "topic": "Basic 2D Shapes",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is 7 multiplied by 4 (7 × 4)? ✖️",
            "options": ["A) 28", "B) 24", "C) 32", "D) 21"],
            "correctAnswer": "A",
            "explanation": "7 × 4 = 28.",
            "topic": "Multiplication Tables",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If you have 50 rupees and buy a chocolate for 20 rupees, how much money is left? 🍫",
            "options": ["A) 30 Rupees", "B) 25 Rupees", "C) 35 Rupees", "D) 20 Rupees"],
            "correctAnswer": "A",
            "explanation": "50 - 20 = 30 rupees remaining.",
            "topic": "Money & Subtraction",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which of these numbers is an EVEN number? 🔢",
            "options": ["A) 18", "B) 15", "C) 21", "D) 9"],
            "correctAnswer": "A",
            "explanation": "Even numbers are cleanly divisible by 2 and end in 0, 2, 4, 6, or 8. 18 is even.",
            "topic": "Odd & Even Numbers",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the place value of 6 in the number 462? 🎯",
            "options": ["A) 60 (Tens)", "B) 600 (Hundreds)", "C) 6 (Ones)", "D) 6000 (Thousands)"],
            "correctAnswer": "A",
            "explanation": "In 462, 4 is hundreds (400), 6 is tens (60), and 2 is ones (2).",
            "topic": "Place Value",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "How many minutes are there in ONE full hour? ⏱️",
            "options": ["A) 60 minutes", "B) 100 minutes", "C) 30 minutes", "D) 24 minutes"],
            "correctAnswer": "A",
            "explanation": "There are 60 minutes in 1 hour.",
            "topic": "Time Measurement",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is 80 minus 35 (80 - 35)? ➖",
            "options": ["A) 45", "B) 55", "C) 40", "D) 50"],
            "correctAnswer": "A",
            "explanation": "80 - 35 = 45.",
            "topic": "Subtraction",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "A square has how many equal sides? 🔲",
            "options": ["A) 4 equal sides", "B) 3 sides", "C) 5 sides", "D) 0 sides"],
            "correctAnswer": "A",
            "explanation": "A square has 4 straight sides of equal length and 4 right angles.",
            "topic": "Basic 2D Shapes",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is 9 × 5? 🌟",
            "options": ["A) 45", "B) 40", "C) 54", "D) 36"],
            "correctAnswer": "A",
            "explanation": "9 × 5 = 45.",
            "topic": "Multiplication Tables",
            "marks": 1,
        },
    ],
    "science": [
        {
            "type": "mcq",
            "questionText": "What part of a plant absorbs water and minerals from deep under the soil? 🌱",
            "options": ["A) Roots", "B) Flower", "C) Leaves", "D) Fruit"],
            "correctAnswer": "A",
            "explanation": "Roots hold the plant firmly in the soil and absorb water and essential nutrients.",
            "topic": "Plants Around Us",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which animal is famous as the 'Ship of the Desert'? 🐪",
            "options": ["A) Camel", "B) Elephant", "C) Lion", "D) Horse"],
            "correctAnswer": "A",
            "explanation": "Camels can survive for weeks without water and walk effortlessly across sandy dunes.",
            "topic": "Animal Habitats",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Ice is which physical state of water? 🧊",
            "options": ["A) Solid", "B) Liquid", "C) Gas", "D) Plasma"],
            "correctAnswer": "A",
            "explanation": "Water freezes into ice at 0°C, turning into a solid state.",
            "topic": "States of Matter",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which human sense organ helps us hear songs and sounds? 👂",
            "options": ["A) Ears", "B) Eyes", "C) Nose", "D) Tongue"],
            "correctAnswer": "A",
            "explanation": "Our ears receive sound vibrations allowing us to hear.",
            "topic": "Our Sense Organs",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What gives green color to the leaves of plants? 🍃",
            "options": ["A) Chlorophyll", "B) Sunlight", "C) Carbon", "D) Sugar"],
            "correctAnswer": "A",
            "explanation": "Chlorophyll is the green pigment in leaves that captures sunlight for photosynthesis.",
            "topic": "Plant Life",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "The Earth gets heat and light energy naturally from the: ☀️",
            "options": ["A) Sun", "B) Moon", "C) Stars", "D) Wind"],
            "correctAnswer": "A",
            "explanation": "The Sun is our closest star and the primary source of light and heat for Earth.",
            "topic": "Solar System & Space",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Animals that eat ONLY plants and grass are called: 🌿",
            "options": ["A) Herbivores", "B) Carnivores", "C) Omnivores", "D) Predators"],
            "correctAnswer": "A",
            "explanation": "Herbivores (like cows, deer, and rabbits) feed only on plant matter.",
            "topic": "Animal Diets",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Water boiling in a kettle turns into water vapor. This process is called: 💨",
            "options": ["A) Evaporation", "B) Freezing", "C) Melting", "D) Condensation"],
            "correctAnswer": "A",
            "explanation": "Evaporation is the phase change from liquid to gas (water vapor).",
            "topic": "Water Cycle",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "How many bones make up an adult human skeleton? 🦴",
            "options": ["A) 206", "B) 150", "C) 300", "D) 100"],
            "correctAnswer": "A",
            "explanation": "An adult human body has 206 bones in the skeletal system.",
            "topic": "Human Body",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which gas do human beings breathe IN to stay alive? 🌬️",
            "options": ["A) Oxygen", "B) Carbon Dioxide", "C) Nitrogen", "D) Helium"],
            "correctAnswer": "A",
            "explanation": "Humans inhale Oxygen for cellular respiration and exhale Carbon Dioxide.",
            "topic": "Living Things",
            "marks": 1,
        },
    ],
    "english": [
        {
            "type": "mcq",
            "questionText": "Which of the following words is a NOUN (naming word)? 📚",
            "options": ["A) School", "B) Quickly", "C) Sing", "D) Beautiful"],
            "correctAnswer": "A",
            "explanation": "A noun is the name of a person, place, or thing. 'School' is a place.",
            "topic": "Nouns & Parts of Speech",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the correct article: 'Anjali eats ___ apple every morning.' 🍎",
            "options": ["A) an", "B) a", "C) the", "D) no article"],
            "correctAnswer": "A",
            "explanation": "We use 'an' before words beginning with a vowel sound (a, e, i, o, u).",
            "topic": "Articles (A, An, The)",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the plural form of the word 'Child'? 🧒",
            "options": ["A) Children", "B) Childs", "C) Childrens", "D) Childes"],
            "correctAnswer": "A",
            "explanation": "The irregular plural form of child is 'children'.",
            "topic": "Plurals",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the OPPOSITE (antonym) of the word 'Happy'? 😢",
            "options": ["A) Sad", "B) Joyful", "C) Glad", "D) Excited"],
            "correctAnswer": "A",
            "explanation": "'Sad' is the antonym of happy.",
            "topic": "Antonyms & Synonyms",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Find the ACTION word (verb) in this sentence: 'Birds fly in the blue sky.' 🕊️",
            "options": ["A) Fly", "B) Birds", "C) Sky", "D) Blue"],
            "correctAnswer": "A",
            "explanation": "'Fly' is an action verb describing what the birds are doing.",
            "topic": "Verbs & Actions",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which punctuation mark comes at the end of a question? ❓",
            "options": ["A) Question mark (?)", "B) Full stop (.)", "C) Comma (,)", "D) Exclamation mark (!)"],
            "correctAnswer": "A",
            "explanation": "A question mark (?) is placed at the end of an interrogative sentence.",
            "topic": "Punctuation",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the correct spelling: 🎨",
            "options": ["A) Beautiful", "B) Beautifull", "C) Beatiful", "D) Beauteful"],
            "correctAnswer": "A",
            "explanation": "The correct spelling is 'Beautiful'.",
            "topic": "Spelling Mastery",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the past tense of the verb 'Go'? 🚶",
            "options": ["A) Went", "B) Gone", "C) Goes", "D) Going"],
            "correctAnswer": "A",
            "explanation": "The past simple form of 'go' is 'went'.",
            "topic": "Tenses",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "A word that describes a noun (like 'A red car') is called: 🚗",
            "options": ["A) Adjective", "B) Verb", "C) Pronoun", "D) Conjunction"],
            "correctAnswer": "A",
            "explanation": "An adjective describes qualities of a noun (color, size, texture).",
            "topic": "Adjectives",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the synonym (similar meaning) of the word 'Large'? 🐘",
            "options": ["A) Big", "B) Tiny", "C) Short", "D) Narrow"],
            "correctAnswer": "A",
            "explanation": "'Big' means the same as large.",
            "topic": "Synonyms",
            "marks": 1,
        },
    ]
}

# Standard Secondary / Senior Curriculum Bank (Class 5-12)
SECONDARY_QUESTION_BANKS = {
    "computer science": [
        {
            "type": "mcq",
            "questionText": "Which data structure follows the LIFO (Last In First Out) principle?",
            "options": ["A) Stack", "B) Queue", "C) Linked List", "D) Binary Tree"],
            "correctAnswer": "A",
            "explanation": "In a Stack, the element added last is the first one to be removed (LIFO).",
            "topic": "Data Structures",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "In Python, which keyword is used to define an anonymous or inline function?",
            "options": ["A) lambda", "B) def", "C) inline", "D) func"],
            "correctAnswer": "A",
            "explanation": "The 'lambda' keyword defines small anonymous functions in Python.",
            "topic": "Python Programming",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the binary representation of the decimal number 13?",
            "options": ["A) 1101", "B) 1011", "C) 1110", "D) 1001"],
            "correctAnswer": "A",
            "explanation": "13 in binary is 8 + 4 + 0 + 1 = 1101.",
            "topic": "Number Systems",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "In SQL, which clause is used to filter groups created by the GROUP BY clause?",
            "options": ["A) HAVING", "B) WHERE", "C) ORDER BY", "D) LIMIT"],
            "correctAnswer": "A",
            "explanation": "HAVING filters aggregated groups, whereas WHERE filters individual table rows.",
            "topic": "Relational Databases",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the worst-case time complexity of Binary Search on a sorted array of size n?",
            "options": ["A) O(log n)", "B) O(n)", "C) O(n log n)", "D) O(1)"],
            "correctAnswer": "A",
            "explanation": "Binary search divides the search space in half at each step, giving O(log n) time.",
            "topic": "Algorithms",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which protocol is responsible for resolving a domain name into an IP address?",
            "options": ["A) DNS", "B) DHCP", "C) HTTP", "D) FTP"],
            "correctAnswer": "A",
            "explanation": "DNS (Domain Name System) translates human-readable hostnames into numeric IP addresses.",
            "topic": "Computer Networks",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "According to De Morgan's Law in Boolean Logic, (A + B)' equals:",
            "options": ["A) A' · B'", "B) A' + B'", "C) (A · B)'", "D) A · B"],
            "correctAnswer": "A",
            "explanation": "De Morgan's First Law states (A + B)' = A' · B'.",
            "topic": "Boolean Algebra",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which Python data type is immutable?",
            "options": ["A) Tuple", "B) List", "C) Set", "D) Dictionary"],
            "correctAnswer": "A",
            "explanation": "Tuples cannot be altered once created, making them immutable.",
            "topic": "Python Programming",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What does CSS stand for in web development?",
            "options": ["A) Cascading Style Sheets", "B) Creative Style System", "C) Computer Styled Syntax", "D) Color and Style Standards"],
            "correctAnswer": "A",
            "explanation": "CSS stands for Cascading Style Sheets, used to style HTML elements.",
            "topic": "Web Technologies",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "In Object-Oriented Programming, wrapping data and methods into a single unit is known as:",
            "options": ["A) Encapsulation", "B) Inheritance", "C) Polymorphism", "D) Abstraction"],
            "correctAnswer": "A",
            "explanation": "Encapsulation binds data attributes with the methods that operate on that data.",
            "topic": "OOP Principles",
            "marks": 1,
        },
    ],
    "mathematics": [
        {
            "type": "mcq",
            "questionText": "For a quadratic equation ax² + bx + c = 0 with discriminant D = 0, the roots are:",
            "options": ["A) Two equal real roots", "B) Two distinct real roots", "C) Imaginary roots", "D) Three real roots"],
            "correctAnswer": "A",
            "explanation": "When discriminant D = b² - 4ac = 0, roots are coincident and real: x = -b/(2a).",
            "topic": "Quadratic Equations",
            "marks": 1,
        },
        {
            "type": "numerical",
            "questionText": "Find the 10th term of the Arithmetic Progression: 2, 5, 8, 11...",
            "correctAnswer": "29",
            "explanation": "a = 2, d = 3. a_10 = a + (10 - 1)d = 2 + (9)(3) = 29.",
            "topic": "Arithmetic Progression",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the value of sin²(30°) + cos²(30°)?",
            "options": ["A) 1", "B) 0", "C) 1/2", "D) √3/2"],
            "correctAnswer": "A",
            "explanation": "By the Pythagorean trigonometric identity, sin²(θ) + cos²(θ) = 1 for any angle θ.",
            "topic": "Trigonometry",
            "marks": 1,
        },
        {
            "type": "numerical",
            "questionText": "If the radius of a circle is 7 cm, calculate its circumference in cm (use π = 22/7):",
            "correctAnswer": "44",
            "explanation": "Circumference = 2πr = 2 * (22/7) * 7 = 44 cm.",
            "topic": "Mensuration",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If a fair die is rolled once, what is the probability of rolling a prime number?",
            "options": ["A) 1/2", "B) 1/3", "C) 2/3", "D) 1/6"],
            "correctAnswer": "A",
            "explanation": "Prime outcomes on a die are {2, 3, 5} -> 3 favorable out of 6 total = 3/6 = 1/2.",
            "topic": "Probability",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Find the slope (gradient) of the line passing through (2, 3) and (6, 11):",
            "options": ["A) 2", "B) 3", "C) 4", "D) 1/2"],
            "correctAnswer": "A",
            "explanation": "Slope m = (y2 - y1) / (x2 - x1) = (11 - 3) / (6 - 2) = 8 / 4 = 2.",
            "topic": "Coordinate Geometry",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If the volume of a cube is 125 cm³, what is the length of its edge?",
            "options": ["A) 5 cm", "B) 25 cm", "C) 15 cm", "D) 10 cm"],
            "correctAnswer": "A",
            "explanation": "Volume = a³ = 125 -> a = ∛125 = 5 cm.",
            "topic": "Mensuration",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "The mean of the numbers 4, 8, 12, 16, and 20 is:",
            "options": ["A) 12", "B) 10", "C) 14", "D) 16"],
            "correctAnswer": "A",
            "explanation": "Sum = 4 + 8 + 12 + 16 + 20 = 60. Mean = 60 / 5 = 12.",
            "topic": "Statistics",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Solve for x: 3x - 7 = 14",
            "options": ["A) 7", "B) 5", "C) 21", "D) 3"],
            "correctAnswer": "A",
            "explanation": "3x = 14 + 7 = 21 -> x = 7.",
            "topic": "Linear Equations",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the hypotenuse of a right-angled triangle with sides 6 cm and 8 cm?",
            "options": ["A) 10 cm", "B) 14 cm", "C) 12 cm", "D) 9 cm"],
            "correctAnswer": "A",
            "explanation": "h = √(6² + 8²) = √(36 + 64) = √100 = 10 cm.",
            "topic": "Pythagoras Theorem",
            "marks": 1,
        },
    ],
    "english": [
        {
            "type": "mcq",
            "questionText": "Identify the passive voice for: 'The chef prepared a magnificent dinner.'",
            "options": [
                "A) A magnificent dinner was prepared by the chef.",
                "B) A magnificent dinner is being prepared by the chef.",
                "C) The chef was preparing dinner.",
                "D) Dinner has been prepared by chef."
            ],
            "correctAnswer": "A",
            "explanation": "Simple past active 'prepared' transforms to 'was prepared' in passive voice.",
            "topic": "Active and Passive Voice",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which of the following is a complex sentence?",
            "options": [
                "A) Although it was raining, we decided to play outside.",
                "B) She bought apples and oranges from the grocery store.",
                "C) The train arrived on time.",
                "D) He worked hard, so he passed the exam."
            ],
            "correctAnswer": "A",
            "explanation": "A complex sentence contains one independent clause and at least one dependent clause introduced by a subordinating conjunction ('Although').",
            "topic": "Sentence Structures",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the correct indirect speech for: He said, 'I am reading a novel.'",
            "options": [
                "A) He said that he was reading a novel.",
                "B) He says that he is reading a novel.",
                "C) He said that he read a novel.",
                "D) He told that he had read a novel."
            ],
            "correctAnswer": "A",
            "explanation": "Present continuous 'am reading' shifts to past continuous 'was reading' in reported speech.",
            "topic": "Direct & Indirect Speech",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What figure of speech is used in: 'The classroom was a zoo during the break'?",
            "options": ["A) Metaphor", "B) Simile", "C) Personification", "D) Hyperbole"],
            "correctAnswer": "A",
            "explanation": "A metaphor directly equates one thing to another without using 'like' or 'as'.",
            "topic": "Figures of Speech",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Select the antonym for the word 'Candid':",
            "options": ["A) Deceitful", "B) Honest", "C) Frank", "D) Sincere"],
            "correctAnswer": "A",
            "explanation": "'Candid' means truthful and straightforward; its antonym is 'Deceitful'.",
            "topic": "Vocabulary & Antonyms",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the correctly punctuated sentence:",
            "options": [
                "A) However, the team did not give up hope.",
                "B) However the team did not give up, hope.",
                "C) However the team, did not give up hope.",
                "D) However; the team did not give up hope."
            ],
            "correctAnswer": "A",
            "explanation": "Introductory transition words like 'However' must be followed by a comma.",
            "topic": "Punctuation & Grammar",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What does the idiom 'Bite the bullet' mean?",
            "options": [
                "A) Face a difficult situation with courage",
                "B) Eat metallic objects",
                "C) Avoid responsibility",
                "D) Act foolishly in public"
            ],
            "correctAnswer": "A",
            "explanation": "'Bite the bullet' means to bravely endure an inevitable and challenging situation.",
            "topic": "Idioms and Phrases",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Fill in the blank with the correct modal verb: 'You ___ wear a helmet while riding a motorcycle.'",
            "options": ["A) must", "B) might", "C) could", "D) may"],
            "correctAnswer": "A",
            "explanation": "'Must' expresses strong legal obligation and vital safety necessity.",
            "topic": "Modal Auxiliaries",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Identify the subject in the sentence: 'Under the old wooden bridge lives a family of otters.'",
            "options": ["A) A family of otters", "B) The old wooden bridge", "C) Lives", "D) Under"],
            "correctAnswer": "A",
            "explanation": "In an inverted sentence, the noun phrase performing the action ('A family of otters') is the subject.",
            "topic": "Subject-Verb Agreement",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the correct prefix to form the opposite of 'Legible':",
            "options": ["A) Il-", "B) Un-", "C) Dis-", "D) In-"],
            "correctAnswer": "A",
            "explanation": "The prefix 'Il-' attaches to words starting with 'L' to denote negation (Illegible).",
            "topic": "Prefixes & Suffixes",
            "marks": 1,
        },
    ],
    "science": [
        {
            "type": "mcq",
            "questionText": "Which cell organelle is commonly referred to as the 'Powerhouse of the Cell'?",
            "options": ["A) Mitochondria", "B) Ribosome", "C) Golgi Apparatus", "D) Nucleus"],
            "correctAnswer": "A",
            "explanation": "Mitochondria generate cellular energy in the form of ATP through cellular respiration.",
            "topic": "Cell Biology",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the chemical formula of common baking soda?",
            "options": ["A) NaHCO₃", "B) Na₂CO₃", "C) NaCl", "D) NaOH"],
            "correctAnswer": "A",
            "explanation": "Sodium hydrogen carbonate (Sodium Bicarbonate, NaHCO₃) is baking soda.",
            "topic": "Acids, Bases & Salts",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which law of motion gives the fundamental definition of Force as F = ma?",
            "options": [
                "A) Newton's Second Law",
                "B) Newton's First Law",
                "C) Newton's Third Law",
                "D) Law of Gravitation"
            ],
            "correctAnswer": "A",
            "explanation": "Newton's Second Law states that the rate of change of momentum is proportional to applied force (F = ma).",
            "topic": "Laws of Motion",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which metal remains in liquid state at standard room temperature?",
            "options": ["A) Mercury (Hg)", "B) Sodium (Na)", "C) Lead (Pb)", "D) Gallium (Ga)"],
            "correctAnswer": "A",
            "explanation": "Mercury is the only elemental metal that is liquid at standard room temperature (25°C).",
            "topic": "Metals and Non-Metals",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "The phenomenon of splitting white light into its component colors through a prism is called:",
            "options": ["A) Dispersion", "B) Refraction", "C) Total Internal Reflection", "D) Diffraction"],
            "correctAnswer": "A",
            "explanation": "Dispersion is the separation of white light into its spectrum of colors due to varying wavelengths.",
            "topic": "Light and Optics",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the pH value of pure distilled water at 25°C?",
            "options": ["A) 7.0 (Neutral)", "B) 5.5 (Acidic)", "C) 8.5 (Basic)", "D) 0.0"],
            "correctAnswer": "A",
            "explanation": "Pure water has equal concentrations of H⁺ and OH⁻ ions, giving a neutral pH of 7.",
            "topic": "Chemical Equilibrium",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which blood group is universally known as the 'Universal Donor'?",
            "options": ["A) O Negative (O-)", "B) AB Positive (AB+)", "C) A Positive (A+)", "D) B Negative (B-)"],
            "correctAnswer": "A",
            "explanation": "O-negative red blood cells lack A, B, and Rh surface antigens, preventing immune rejection.",
            "topic": "Circulatory System",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "The device used to measure electric current in a circuit is called an:",
            "options": ["A) Ammeter", "B) Voltmeter", "C) Galvanometer", "D) Ohmmeter"],
            "correctAnswer": "A",
            "explanation": "An ammeter is connected in series in an electric circuit to measure electric current in Amperes.",
            "topic": "Electricity & Magnetism",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What type of chemical reaction occurs when methane burns in oxygen to form CO₂ and water?",
            "options": ["A) Combustion (Exothermic)", "B) Endothermic Decomposition", "C) Precipitation", "D) Displacement"],
            "correctAnswer": "A",
            "explanation": "Hydrocarbon oxidation with rapid heat and light release is a combustion reaction.",
            "topic": "Chemical Reactions",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which layer of the atmosphere contains the protective ozone layer that absorbs harmful UV rays?",
            "options": ["A) Stratosphere", "B) Troposphere", "C) Mesosphere", "D) Thermosphere"],
            "correctAnswer": "A",
            "explanation": "The Stratosphere contains the highest concentration of ozone (O₃), filtering harmful solar UV-B radiation.",
            "topic": "Environmental Science",
            "marks": 1,
        },
    ],
    "social studies": [
        {
            "type": "mcq",
            "questionText": "Who is revered as the 'Father of the Indian Constitution'?",
            "options": ["A) Dr. B.R. Ambedkar", "B) Mahatma Gandhi", "C) Jawaharlal Nehru", "D) Sardar Vallabhbhai Patel"],
            "correctAnswer": "A",
            "explanation": "Dr. Bhimrao Ramji Ambedkar served as the Chairman of the Drafting Committee of the Constitution of India.",
            "topic": "Indian Polity & Constitution",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which imaginary line divides the Earth into the Northern and Southern Hemispheres?",
            "options": ["A) Equator (0° Latitude)", "B) Prime Meridian (0° Longitude)", "C) Tropic of Cancer", "D) Tropic of Capricorn"],
            "correctAnswer": "A",
            "explanation": "The Equator is the 0° parallel of latitude dividing Earth into Northern and Southern halves.",
            "topic": "Physical Geography",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "In which year did the historic Revolt of 1857 (Sepoy Mutiny) break out in India?",
            "options": ["A) 1857", "B) 1757", "C) 1947", "D) 1885"],
            "correctAnswer": "A",
            "explanation": "The first major armed uprising against British East India Company rule began in 1857 at Meerut.",
            "topic": "Modern Indian History",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which tier of government in India operates at the local village grassroots level?",
            "options": ["A) Gram Panchayat (Panchayati Raj)", "B) Municipal Corporation", "C) State Legislature", "D) Parliament"],
            "correctAnswer": "A",
            "explanation": "The 73rd Constitutional Amendment Act established the 3-tier Panchayati Raj system with Gram Panchayat at the village base.",
            "topic": "Local Self Government",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which is the longest river in peninsular India?",
            "options": ["A) Godavari", "B) Krishna", "C) Narmada", "D) Kaveri"],
            "correctAnswer": "A",
            "explanation": "The Godavari River is known as 'Dakshin Ganga' and is the longest peninsular river in India (approx 1,465 km).",
            "topic": "Drainage Systems",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Fundamental Rights of Indian Citizens are enshrined in which part of the Constitution?",
            "options": ["A) Part III (Articles 12-35)", "B) Part IV", "C) Part II", "D) Part I"],
            "correctAnswer": "A",
            "explanation": "Part III of the Constitution guarantees six Fundamental Rights to all Indian citizens.",
            "topic": "Indian Civics",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "The Industrial Revolution first began during the mid-18th century in which country?",
            "options": ["A) Great Britain", "B) United States", "C) France", "D) Germany"],
            "correctAnswer": "A",
            "explanation": "Britain's abundant coal, iron ore, and steam power innovations catalyzed the Industrial Revolution.",
            "topic": "World History",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Which type of soil is most suitable for cotton cultivation in India?",
            "options": ["A) Black Soil (Regur Soil)", "B) Alluvial Soil", "C) Red Soil", "D) Laterite Soil"],
            "correctAnswer": "A",
            "explanation": "Black soil (Regur) of the Deccan plateau holds moisture excellently, ideal for cotton farming.",
            "topic": "Resources & Agriculture",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Who was the founder of the Maurya Empire in ancient India?",
            "options": ["A) Chandragupta Maurya", "B) Ashoka the Great", "C) Bindusara", "D) Samudragupta"],
            "correctAnswer": "A",
            "explanation": "Chandragupta Maurya founded the Maurya Empire in 322 BCE with the guidance of Chanakya (Kautilya).",
            "topic": "Ancient History",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "What is the minimum voting age for Indian citizens as per the 61st Constitutional Amendment?",
            "options": ["A) 18 Years", "B) 21 Years", "C) 16 Years", "D) 25 Years"],
            "correctAnswer": "A",
            "explanation": "The 61st Amendment Act reduced the voting age from 21 to 18 years for Lok Sabha and Assembly elections.",
            "topic": "Elections & Democracy",
            "marks": 1,
        },
    ],
    "logical reasoning": [
        {
            "type": "mcq",
            "questionText": "Find the next number in the series: 3, 6, 12, 24, 48, ___",
            "options": ["A) 96", "B) 72", "C) 84", "D) 100"],
            "correctAnswer": "A",
            "explanation": "Each number is multiplied by 2. 48 × 2 = 96.",
            "topic": "Number Series",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If BOOK is coded as 43, what is the code for PEN (P=16, E=5, N=14)?",
            "options": ["A) 35", "B) 32", "C) 40", "D) 30"],
            "correctAnswer": "A",
            "explanation": "Sum of alphabetical positions: 16 + 5 + 14 = 35.",
            "topic": "Coding-Decoding",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Pointing to a photograph, Rohit said, 'She is the mother of my father's only son.' Who is she to Rohit?",
            "options": ["A) Mother", "B) Sister", "C) Aunt", "D) Grandmother"],
            "correctAnswer": "A",
            "explanation": "Rohit's father's only son is Rohit himself. Her mother is Rohit's mother.",
            "topic": "Blood Relations",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "A clock shows 3:00. What is the angle between the hour hand and the minute hand?",
            "options": ["A) 90°", "B) 60°", "C) 120°", "D) 45°"],
            "correctAnswer": "A",
            "explanation": "At 3:00, the minute hand is at 12 and the hour hand is at 3, creating a 90° right angle.",
            "topic": "Clock Problems",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Choose the odd one out:",
            "options": ["A) Triangle", "B) Square", "C) Rectangle", "D) Circle"],
            "correctAnswer": "D",
            "explanation": "Circle is curved, while Triangle, Square, and Rectangle are polygons made of straight line segments.",
            "topic": "Classification",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If South-East becomes North, North-East becomes West, and so on, what will West become?",
            "options": ["A) South-East", "B) North-East", "C) South-West", "D) North-West"],
            "correctAnswer": "A",
            "explanation": "The direction turns 135° clockwise. West + 135° clockwise becomes South-East.",
            "topic": "Direction Sense",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "In a row of 25 students, Priya is 10th from the left. What is her rank from the right end?",
            "options": ["A) 16th", "B) 15th", "C) 17th", "D) 14th"],
            "correctAnswer": "A",
            "explanation": "Rank from right = Total - Rank from left + 1 = 25 - 10 + 1 = 16th.",
            "topic": "Order & Ranking",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Doctor is related to Hospital in the same way as Teacher is related to:",
            "options": ["A) School", "B) Student", "C) Book", "D) Class"],
            "correctAnswer": "A",
            "explanation": "A Doctor works at a Hospital; a Teacher works at a School (Profession : Workplace).",
            "topic": "Analogies",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "Statements: All cats are animals. All animals are living beings. Conclusion: All cats are living beings.",
            "options": ["A) Definite True", "B) Definite False", "C) Cannot be determined", "D) Partially True"],
            "correctAnswer": "A",
            "explanation": "By syllogism transitive rule: Cats ⊆ Animals ⊆ Living Beings, thus All Cats are Living Beings.",
            "topic": "Syllogisms & Logic",
            "marks": 1,
        },
        {
            "type": "mcq",
            "questionText": "If '+' means '×', '×' means '÷', and '÷' means '+', what is 8 + 4 ÷ 6 × 2?",
            "options": ["A) 35", "B) 32", "C) 28", "D) 38"],
            "correctAnswer": "A",
            "explanation": "8 × 4 + (6 ÷ 2) = 32 + 3 = 35.",
            "topic": "Mathematical Operations",
            "marks": 1,
        },
    ],
}


def build_fallback_questions(
    board: str,
    subject: str,
    difficulty: str,
    ref_links: list[dict] | None = None,
    class_grade: str = "Class 3",
    limit: int = 5,
    force_mcq: bool = False,
) -> list[dict]:
    """Generates deterministic, grade-appropriate, subject-matched curriculum questions
    matching the exact question count requested.
    """
    clean_subj = (subject or "General Assessment").lower().strip()
    clean_grade = (class_grade or "").lower().strip()
    is_kid = any(k in clean_grade for k in ["class 1", "class 2", "class 3", "class 4"])

    # Determine bank category
    bank_map = KIDS_QUESTION_BANKS if is_kid else SECONDARY_QUESTION_BANKS
    matched_questions: list[dict] = []

    if "comput" in clean_subj or "code" in clean_subj or "it" in clean_subj or "ai" in clean_subj:
        matched_questions = bank_map.get("computer science", [])
    elif "math" in clean_subj or "algebra" in clean_subj or "calculus" in clean_subj:
        matched_questions = bank_map.get("mathematics", [])
    elif "eng" in clean_subj or "gramm" in clean_subj:
        matched_questions = bank_map.get("english", [])
    elif "logic" in clean_subj or "reason" in clean_subj or "aptitude" in clean_subj:
        matched_questions = bank_map.get("logical reasoning", bank_map.get("mathematics", []))
    elif "social" in clean_subj or "hist" in clean_subj or "civic" in clean_subj or "geog" in clean_subj or "sst" in clean_subj:
        matched_questions = bank_map.get("social studies", bank_map.get("science" if is_kid else "physics", []))
    elif "sci" in clean_subj or "phys" in clean_subj or "chem" in clean_subj or "bio" in clean_subj or "evs" in clean_subj:
        matched_questions = bank_map.get("science" if is_kid else "science", bank_map.get("physics", []))
    else:
        # Fallback to subject list or combine
        matched_questions = bank_map.get("computer science" if "comp" in clean_subj else "science" if is_kid else "mathematics", [])

    if not matched_questions:
        matched_questions = KIDS_QUESTION_BANKS["science"] if is_kid else SECONDARY_QUESTION_BANKS["computer science"]

    # Assemble questions up to limit
    result = []
    pool = list(matched_questions)
    
    # If limit is larger than pool, cycle or generate parametric variants
    while len(result) < limit:
        for idx, item in enumerate(pool):
            if len(result) >= limit:
                break
            q_copy = dict(item)
            q_num = len(result) + 1
            q_copy["questionNumber"] = q_num
            q_copy["difficulty"] = difficulty
            if force_mcq:
                q_copy["type"] = "mcq"
                q_copy["marks"] = 1
                if not q_copy.get("options") or len(q_copy.get("options", [])) < 2:
                    corr = q_copy.get("correctAnswer", "A")
                    q_copy["options"] = [f"A) {corr}", "B) Alternative Option B", "C) Alternative Option C", "D) Alternative Option D"]
                    q_copy["correctAnswer"] = "A"
            result.append(q_copy)
        if not pool:
            break

    return result
